In [2]:
import numpy as np
from sklearn.linear_model import LinearRegression
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
X

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3]])

In [6]:
coefs = np.array([1, 2])
y = np.dot(X, coefs) + 3
y

array([ 6,  8,  9, 11])

In [16]:
reg = LinearRegression().fit(X, y)
reg.score(X, y)

1.0

In [17]:
reg.coef_

array([1., 2.])

In [20]:
reg.predict(np.array([[4,7],[6,15]]))

array([21., 39.])